# Generated by Django 2.0.3 on 2020-01-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abay', '0003_auto_20200108_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abay.Customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abay.Order')),
                ('product', models.ManyToManyField(to='abay.Product')),
            ],
        ),
    ]
